events {}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        # Ensure correct MIME for SVG
        location ~* \.svg$ {
            add_header Content-Type image/svg+xml;
        }
    }
}
